version: '3'

services:
  polyplace:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: polyplace
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
